baseurl = "/"
title = "Lahvak's Sample Space"
author = "Jan Hlavacek"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

[permalinks]
    post = "/:year/:month/:day/:slug/"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "The Sample Space"
  GithubEdit = "https://github.com/lahvak/sample.space/edit/master/content/"
  utterancesRepo = "lahvak/sample.space"

[[menu.main]]
    name = "Home"
    url = "https://space.lahvak.space/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lahvak"
    weight = 5
[[menu.main]]
    name = "twtxt"
    url = "http://twtxt.xyz/user/4802a8d4657c9fa0"
    weight = 6
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 7
