---
title: "Limits Using Polar Coordinates"
author: "Jan Hlavacek"
date: '2019-10-08'
slug: limits-using-polar-coordinates
tags:
- Calculus
- Multivariable
- Polar coordinates
categories: Math
draft: true
---

```{r}
library(tidyverse)
library(gganimate)
```

```{r}
df <- data.frame(x=0, param = seq(0,2*pi,.1))
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
f <- function(x,y) {
  return(x*y^2/(x^2 + y^4))
}

theta = seq(0, 2*pi, 0.01)
r = seq(1, .005, -0.005)^3/10

inputs <- data.frame(theta = rep(theta, length(r)),
                     r = rep(r, each = length(theta)))

inputs %>%
  mutate(
    x = r*cos(theta),
    y = r*sin(theta),
    out = f(x, y)) %>%
  ggplot(mapping = aes(x = theta, y = out)) +
    geom_line() +
    transition_time(-r) -> p

animate(p, nframes = length(r), renderer = ffmpeg_renderer())
```

\(\frac{xy^2}{x^2 + y^4} = \frac{r^3\cos(\theta)\sin^2(\theta)}{r^2(\cos^2(\theta) + r^2\sin^4(\theta))}
= \frac{r\cos(\theta)\sin^2(\theta)}{\cos^2(\theta) + r^2\sin^4(\theta)}\)

```{r}
theta = seq(pi/2-0.1, pi/2+0.1, 0.001)

inputs <- data.frame(theta = rep(theta, length(r)),
                     r = rep(r, each = length(theta)))

inputs %>%
  mutate(
    x = r*cos(theta),
    y = r*sin(theta),
    out = f(x, y)) %>%
  ggplot(mapping = aes(x = theta, y = out)) +
    geom_line() +
    transition_time(-r) -> p

animate(p, nframes = length(r), renderer = ffmpeg_renderer())
```
