---
title: Another stupid word problem
author: Jan Hlavacek
date: '2019-12-10'
slug: another-stupid-word-problem
categories:
  - Math
  - Teaching
tags:
  - math
  - rant
---

So I am grading intro algebra exams, and there is this problem:

_The product of two consecutive positive even integers in 168.  Find the integers._

Students are supposed to solve this by setting up and solving a quadratic equation $x(x+2) = 168$.  What's stupid about this is that at this moment the only way to solve this equation that the students know is simple factoring, so they have to rewrite the equation as $x^2 + 2x - 168 = 0$ and factor it.  In order to factor this, they need to find two numbers whose difference is 2 and whose product is 168.  In other words, they have to solve the original question.

Of course, should they know how to complete a square, they could instead rewrite the equation as $(x+1)^2 - 169 = 0$.  The left side is now a difference of two squares, so itcan be factored as $(x + 1 + 13)(x + 1 - 13)$.  Now we can start asking more interesting questions, for example _which numbers can be written as a product of two consecutive even or odd integers?_