---
title: How to comment on this blog
author: Jan Hlavacek
date: '2019-04-09'
slug: how-to-comment-on-this-blog
categories:
  - Blog
tags:
  - commenting
  - utterances
---

This blog uses [utterance.es](https://utterance.es/) to enable commenting on posts.
_Utterances_ use GitHub _issues_ to keep track of commens. Basically the way it works is, when you comment, an
_issue_ will be created on GitHub with your comment.  _Utterances_ then finds all issues
related to a post, and displays them as comments at the bottom of the post.

This makes it easy for me, because all your comments are available to me on GitHub, where I can easily access and manage them.

## What it means for you

To post a comment to a post on this blog, you need to make sure that:

1. you have a [GitHub](https://github.com/) account, and
2. you do not block third party cookies from `utteranc.es`.

If you find out that you cannot post a comment even after logging into your GitHub account, it probably means that your browser blocks third party cookies.  In most browsers, even if you block third party cookies, you can add exceptions for individual sites.  To be able to comment on this site, you need to allow cookies from `utteranc.es`.
